[2021-08-15 20:25:39,405] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: testing_airflow.testing_airflow 2021-08-14T00:00:00+00:00 [queued]>
[2021-08-15 20:25:39,411] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: testing_airflow.testing_airflow 2021-08-14T00:00:00+00:00 [queued]>
[2021-08-15 20:25:39,411] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-15 20:25:39,411] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2021-08-15 20:25:39,411] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-15 20:25:39,417] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): testing_airflow> on 2021-08-14T00:00:00+00:00
[2021-08-15 20:25:39,419] {standard_task_runner.py:52} INFO - Started process 70765 to run task
[2021-08-15 20:25:39,426] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'testing_airflow', 'testing_airflow', '2021-08-14T00:00:00+00:00', '--job-id', '42', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/Airflow.py', '--cfg-path', '/var/folders/kh/c93m3t_d2rgcvcbylylqtx240000gn/T/tmp0bqg0067', '--error-file', '/var/folders/kh/c93m3t_d2rgcvcbylylqtx240000gn/T/tmpvr0vw38t']
[2021-08-15 20:25:39,428] {standard_task_runner.py:77} INFO - Job 42: Subtask testing_airflow
[2021-08-15 20:25:39,454] {logging_mixin.py:104} INFO - Running <TaskInstance: testing_airflow.testing_airflow 2021-08-14T00:00:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2021-08-15 20:25:39,479] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=testing_airflow
AIRFLOW_CTX_TASK_ID=testing_airflow
AIRFLOW_CTX_EXECUTION_DATE=2021-08-14T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-14T00:00:00+00:00
[2021-08-15 20:25:39,480] {subprocess.py:52} INFO - Tmp dir root location: 
 /var/folders/kh/c93m3t_d2rgcvcbylylqtx240000gn/T
[2021-08-15 20:25:39,481] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'python /Users/kennethlau/Desktop/a_pipeline.py']
[2021-08-15 20:25:39,487] {subprocess.py:74} INFO - Output:
[2021-08-15 20:25:40,775] {subprocess.py:78} INFO - Traceback (most recent call last):
[2021-08-15 20:25:40,776] {subprocess.py:78} INFO -   File "/Users/kennethlau/Desktop/a_pipeline.py", line 87, in <module>
[2021-08-15 20:25:40,776] {subprocess.py:78} INFO -     main()
[2021-08-15 20:25:40,776] {subprocess.py:78} INFO -   File "/Users/kennethlau/Desktop/a_pipeline.py", line 82, in main
[2021-08-15 20:25:40,777] {subprocess.py:78} INFO -     series1 = read_csv('/Users/kennethlau/Desktop/Program_Exercise/Side_Projects/weather_prediction/temperature.csv', header=0, index_col=0, parse_dates=True,squeeze=True)
[2021-08-15 20:25:40,777] {subprocess.py:78} INFO -   File "/Users/kennethlau/airflow/airflow-tutorial/env_airflow/lib/python3.8/site-packages/pandas/io/parsers.py", line 610, in read_csv
[2021-08-15 20:25:40,777] {subprocess.py:78} INFO -     return _read(filepath_or_buffer, kwds)
[2021-08-15 20:25:40,777] {subprocess.py:78} INFO -   File "/Users/kennethlau/airflow/airflow-tutorial/env_airflow/lib/python3.8/site-packages/pandas/io/parsers.py", line 462, in _read
[2021-08-15 20:25:40,778] {subprocess.py:78} INFO -     parser = TextFileReader(filepath_or_buffer, **kwds)
[2021-08-15 20:25:40,778] {subprocess.py:78} INFO -   File "/Users/kennethlau/airflow/airflow-tutorial/env_airflow/lib/python3.8/site-packages/pandas/io/parsers.py", line 819, in __init__
[2021-08-15 20:25:40,778] {subprocess.py:78} INFO -     self._engine = self._make_engine(self.engine)
[2021-08-15 20:25:40,778] {subprocess.py:78} INFO -   File "/Users/kennethlau/airflow/airflow-tutorial/env_airflow/lib/python3.8/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
[2021-08-15 20:25:40,779] {subprocess.py:78} INFO -     return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
[2021-08-15 20:25:40,779] {subprocess.py:78} INFO -   File "/Users/kennethlau/airflow/airflow-tutorial/env_airflow/lib/python3.8/site-packages/pandas/io/parsers.py", line 1867, in __init__
[2021-08-15 20:25:40,779] {subprocess.py:78} INFO -     self._open_handles(src, kwds)
[2021-08-15 20:25:40,779] {subprocess.py:78} INFO -   File "/Users/kennethlau/airflow/airflow-tutorial/env_airflow/lib/python3.8/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
[2021-08-15 20:25:40,780] {subprocess.py:78} INFO -     self.handles = get_handle(
[2021-08-15 20:25:40,780] {subprocess.py:78} INFO -   File "/Users/kennethlau/airflow/airflow-tutorial/env_airflow/lib/python3.8/site-packages/pandas/io/common.py", line 642, in get_handle
[2021-08-15 20:25:40,780] {subprocess.py:78} INFO -     handle = open(
[2021-08-15 20:25:40,781] {subprocess.py:78} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/Users/kennethlau/Desktop/Program_Exercise/Side_Projects/weather_prediction/temperature.csv'
[2021-08-15 20:25:40,872] {subprocess.py:82} INFO - Command exited with return code 1
[2021-08-15 20:25:40,878] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/kennethlau/airflow/airflow-tutorial/env_airflow/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/kennethlau/airflow/airflow-tutorial/env_airflow/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/kennethlau/airflow/airflow-tutorial/env_airflow/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/Users/kennethlau/airflow/airflow-tutorial/env_airflow/lib/python3.8/site-packages/airflow/operators/bash.py", line 176, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-08-15 20:25:40,880] {taskinstance.py:1544} INFO - Marking task as UP_FOR_RETRY. dag_id=testing_airflow, task_id=testing_airflow, execution_date=20210814T000000, start_date=20210816T002539, end_date=20210816T002540
[2021-08-15 20:25:40,908] {local_task_job.py:149} INFO - Task exited with return code 1
[2021-08-15 22:30:55,501] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: testing_airflow.testing_airflow 2021-08-14T00:00:00+00:00 [queued]>
[2021-08-15 22:30:55,510] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: testing_airflow.testing_airflow 2021-08-14T00:00:00+00:00 [queued]>
[2021-08-15 22:30:55,510] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-15 22:30:55,510] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2021-08-15 22:30:55,510] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-15 22:30:55,517] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): testing_airflow> on 2021-08-14T00:00:00+00:00
[2021-08-15 22:30:55,520] {standard_task_runner.py:52} INFO - Started process 72086 to run task
[2021-08-15 22:30:55,529] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'testing_airflow', 'testing_airflow', '2021-08-14T00:00:00+00:00', '--job-id', '40', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/Airflow.py', '--cfg-path', '/var/folders/kh/c93m3t_d2rgcvcbylylqtx240000gn/T/tmph4rbcpgf', '--error-file', '/var/folders/kh/c93m3t_d2rgcvcbylylqtx240000gn/T/tmpsuucc13v']
[2021-08-15 22:30:55,531] {standard_task_runner.py:77} INFO - Job 40: Subtask testing_airflow
[2021-08-15 22:30:55,568] {logging_mixin.py:104} INFO - Running <TaskInstance: testing_airflow.testing_airflow 2021-08-14T00:00:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2021-08-15 22:30:55,602] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=testing_airflow
AIRFLOW_CTX_TASK_ID=testing_airflow
AIRFLOW_CTX_EXECUTION_DATE=2021-08-14T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-14T00:00:00+00:00
[2021-08-15 22:30:55,603] {subprocess.py:52} INFO - Tmp dir root location: 
 /var/folders/kh/c93m3t_d2rgcvcbylylqtx240000gn/T
[2021-08-15 22:30:55,604] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'python /Users/kennethlau/Desktop/programing_exercise/side_projects/a_pipeline.py']
[2021-08-15 22:30:55,612] {subprocess.py:74} INFO - Output:
[2021-08-15 22:30:55,656] {subprocess.py:78} INFO - python: can't open file '/Users/kennethlau/Desktop/programing_exercise/side_projects/a_pipeline.py': [Errno 2] No such file or directory
[2021-08-15 22:30:55,660] {subprocess.py:82} INFO - Command exited with return code 2
[2021-08-15 22:30:55,668] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/kennethlau/airflow/airflow-tutorial/env_airflow/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/kennethlau/airflow/airflow-tutorial/env_airflow/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/kennethlau/airflow/airflow-tutorial/env_airflow/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/Users/kennethlau/airflow/airflow-tutorial/env_airflow/lib/python3.8/site-packages/airflow/operators/bash.py", line 176, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-08-15 22:30:55,673] {taskinstance.py:1544} INFO - Marking task as UP_FOR_RETRY. dag_id=testing_airflow, task_id=testing_airflow, execution_date=20210814T000000, start_date=20210816T023055, end_date=20210816T023055
[2021-08-15 22:30:55,711] {local_task_job.py:149} INFO - Task exited with return code 1
[2021-08-15 22:36:23,740] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: testing_airflow.testing_airflow 2021-08-14T00:00:00+00:00 [queued]>
[2021-08-15 22:36:23,744] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: testing_airflow.testing_airflow 2021-08-14T00:00:00+00:00 [queued]>
[2021-08-15 22:36:23,744] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-15 22:36:23,744] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2021-08-15 22:36:23,744] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-15 22:36:23,749] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): testing_airflow> on 2021-08-14T00:00:00+00:00
[2021-08-15 22:36:23,751] {standard_task_runner.py:52} INFO - Started process 72421 to run task
[2021-08-15 22:36:23,756] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'testing_airflow', 'testing_airflow', '2021-08-14T00:00:00+00:00', '--job-id', '41', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/Airflow.py', '--cfg-path', '/var/folders/kh/c93m3t_d2rgcvcbylylqtx240000gn/T/tmp578by654', '--error-file', '/var/folders/kh/c93m3t_d2rgcvcbylylqtx240000gn/T/tmpu4ypbywj']
[2021-08-15 22:36:23,758] {standard_task_runner.py:77} INFO - Job 41: Subtask testing_airflow
[2021-08-15 22:36:23,782] {logging_mixin.py:104} INFO - Running <TaskInstance: testing_airflow.testing_airflow 2021-08-14T00:00:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2021-08-15 22:36:23,803] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=testing_airflow
AIRFLOW_CTX_TASK_ID=testing_airflow
AIRFLOW_CTX_EXECUTION_DATE=2021-08-14T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-14T00:00:00+00:00
[2021-08-15 22:36:23,804] {subprocess.py:52} INFO - Tmp dir root location: 
 /var/folders/kh/c93m3t_d2rgcvcbylylqtx240000gn/T
[2021-08-15 22:36:23,804] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'python /Users/kennethlau/Desktop/programing_exercise/side_projects/weather_prediction/a_pipeline.py']
[2021-08-15 22:36:23,809] {subprocess.py:74} INFO - Output:
[2021-08-15 22:36:25,795] {subprocess.py:78} INFO - Traceback (most recent call last):
[2021-08-15 22:36:25,796] {subprocess.py:78} INFO -   File "/Users/kennethlau/Desktop/programing_exercise/side_projects/weather_prediction/a_pipeline.py", line 9, in <module>
[2021-08-15 22:36:25,796] {subprocess.py:78} INFO -     from sklearn.metrics import mean_squared_error
[2021-08-15 22:36:25,797] {subprocess.py:78} INFO - ModuleNotFoundError: No module named 'sklearn'
[2021-08-15 22:36:25,945] {subprocess.py:82} INFO - Command exited with return code 1
[2021-08-15 22:36:25,955] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/kennethlau/airflow/airflow-tutorial/env_airflow/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/kennethlau/airflow/airflow-tutorial/env_airflow/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/kennethlau/airflow/airflow-tutorial/env_airflow/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/Users/kennethlau/airflow/airflow-tutorial/env_airflow/lib/python3.8/site-packages/airflow/operators/bash.py", line 176, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-08-15 22:36:25,961] {taskinstance.py:1544} INFO - Marking task as UP_FOR_RETRY. dag_id=testing_airflow, task_id=testing_airflow, execution_date=20210814T000000, start_date=20210816T023623, end_date=20210816T023625
[2021-08-15 22:36:26,011] {local_task_job.py:149} INFO - Task exited with return code 1
