[2021-08-21 21:49:17,298] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: testing_airflow.testing_airflow 2021-08-14T00:00:00+00:00 [queued]>
[2021-08-21 21:49:17,305] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: testing_airflow.testing_airflow 2021-08-14T00:00:00+00:00 [queued]>
[2021-08-21 21:49:17,305] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-21 21:49:17,305] {taskinstance.py:1088} INFO - Starting attempt 2 of 2
[2021-08-21 21:49:17,305] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-21 21:49:17,311] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): testing_airflow> on 2021-08-14T00:00:00+00:00
[2021-08-21 21:49:17,314] {standard_task_runner.py:52} INFO - Started process 26455 to run task
[2021-08-21 21:49:17,322] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'testing_airflow', 'testing_airflow', '2021-08-14T00:00:00+00:00', '--job-id', '45', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/Airflow.py', '--cfg-path', '/var/folders/kh/c93m3t_d2rgcvcbylylqtx240000gn/T/tmp47k2gspb', '--error-file', '/var/folders/kh/c93m3t_d2rgcvcbylylqtx240000gn/T/tmp7ezq7_3p']
[2021-08-21 21:49:17,325] {standard_task_runner.py:77} INFO - Job 45: Subtask testing_airflow
[2021-08-21 21:49:17,367] {logging_mixin.py:104} INFO - Running <TaskInstance: testing_airflow.testing_airflow 2021-08-14T00:00:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2021-08-21 21:49:17,402] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=testing_airflow
AIRFLOW_CTX_TASK_ID=testing_airflow
AIRFLOW_CTX_EXECUTION_DATE=2021-08-14T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-14T00:00:00+00:00
[2021-08-21 21:49:17,404] {subprocess.py:52} INFO - Tmp dir root location: 
 /var/folders/kh/c93m3t_d2rgcvcbylylqtx240000gn/T
[2021-08-21 21:49:17,405] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'python /Users/kennethlau/Desktop/programing_exercise/side_projects/weather_prediction/a_pipeline.py']
[2021-08-21 21:49:17,414] {subprocess.py:74} INFO - Output:
[2021-08-21 21:50:16,261] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 26455
[2021-08-21 21:50:16,264] {taskinstance.py:1284} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-08-21 21:50:16,267] {subprocess.py:88} INFO - Sending SIGTERM signal to process group
[2021-08-21 21:50:16,293] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/kennethlau/opt/anaconda3/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/kennethlau/opt/anaconda3/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/kennethlau/opt/anaconda3/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/Users/kennethlau/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/bash.py", line 168, in execute
    result = self.subprocess_hook.run_command(
  File "/Users/kennethlau/opt/anaconda3/lib/python3.8/site-packages/airflow/hooks/subprocess.py", line 76, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b''):
  File "/Users/kennethlau/opt/anaconda3/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1286, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-08-21 21:50:16,302] {taskinstance.py:1544} INFO - Marking task as FAILED. dag_id=testing_airflow, task_id=testing_airflow, execution_date=20210814T000000, start_date=20210822T014917, end_date=20210822T015016
[2021-08-21 21:50:16,362] {process_utils.py:66} INFO - Process psutil.Process(pid=26455, status='terminated', exitcode=1, started='21:49:17') (26455) terminated with exit code 1
[2021-08-21 21:50:16,363] {process_utils.py:66} INFO - Process psutil.Process(pid=26456, status='terminated', started='21:49:17') (26456) terminated with exit code None
